retrofit:
  server-port: "8001"
  protocol: "http"
  ip: "localhost"
  baseUrl: ${retrofit.protocol}://${retrofit.ip}:${retrofit.server-port}
spring:
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  jackson:
    date-format: "yyyy-MM-dd'T'HH:mm:ssZ"
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ""
    username: postgres
    password: senha-do-banco
server:
  port: 8002